name: Test

on:
  pull_request:
    paths:
      - "firestore-stripe-web-sdk/**"
    branches:
      - "**"

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firestore-stripe-web-sdk
    steps:
      - uses: actions/checkout@v1
      - name: NPM Install
        run: npm i
      - name: NPM Build
        run: npm run build
      - name: Unit Test
        run: lerna run --scope firestore-stripe-payments test
